// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class constants
{
        public const string achievement_profi = "CgkIhYz47rgREAIQBQ"; // <GPGSID>
        public const string achievement_advanced = "CgkIhYz47rgREAIQBA"; // <GPGSID>
        public const string achievement_impossible = "CgkIhYz47rgREAIQBw"; // <GPGSID>
        public const string achievement_beginner = "CgkIhYz47rgREAIQAg"; // <GPGSID>
        public const string package_name = "com.CoolGames.BalloonFun"; // <GPGSID>
        public const string achievement_amateur = "CgkIhYz47rgREAIQAw"; // <GPGSID>
        public const string achievement_best_of_the_best = "CgkIhYz47rgREAIQBg"; // <GPGSID>
        public const string leaderboard_balloon_fun = "CgkIhYz47rgREAIQAQ"; // <GPGSID>

}

